defaultPlacement: end
fieldLayouts:
  4003219b-56f2-44e2-9781-639b120c251e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 69ae1e6d-eb5d-4707-840a-acdb77b10510
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ee88eb1-eb2a-4e92-9356-a12d8b1bedd9
        userCondition: null
handle: newsCats
name: News
siteSettings:
  5a388334-4b50-4126-b1df-67227ce21818: # $SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 0546f728-c0e4-46b8-8434-3031a00f2fac
